### ISSUE TITLE
npm install -g nysocks遇错，怎么解决？

### ISSUE THREAD

**Issue by luckypoem** [oyyd/nysocks#5]
root@vps:~# npm install -g nysocks
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-QFUCsAfzGcP0cXXER0UnMA8qta0= integrity checksum failed when using sha1: wanted sha1-QFUCsAfzGcP0cXXER0UnMA8qta0= but got sha512-zr6QQnzLt3Ja0t0XI8gws2kn7zV2p0l/D3kreNvS6hFZhVU5g+uY/30l42jbgt0XGcNBEmBDGJR71J692V92tA==. (260 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
/root/node-v9.5.0-linux-x64/bin/nysocks -> /root/node-v9.5.0-linux-x64/lib/node_modules/nysocks/bin/nysocks

> nysocks@1.2.9 install /root/node-v9.5.0-linux-x64/lib/node_modules/nysocks
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/nysocks/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nysocks@1.2.9 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nysocks@1.2.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-15T05_24_21_444Z-debug.log
root@vps:~#

**Comment by oyyd** [comment]
```
sh: 1: node-gyp: Permission denied
```
看起来是权限的问题。问一下你的OS是？

**Comment by luckypoem** [comment]
是debian8:
root@vps:~# cat /etc/issue.net
Debian GNU/Linux 8
root@vps:~#

**Comment by oyyd** [comment]
权限导致的问题，可能的原因有很多，试试直接从源码安装会有问题吗

```
https://github.com/oyyd/nysocks.git
cd nysocks
git checkout 1.2.9
npm i --production
```

**Comment by luckypoem** [comment]
hi.

root@vps:~/nysocks# npm i --production
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-QFUCsAfzGcP0cXXER0UnMA8qta0= integrity checksum failed when using sha1: wanted sha1-QFUCsAfzGcP0cXXER0UnMA8qta0= but got sha512-zr6QQnzLt3Ja0t0XI8gws2kn7zV2p0l/D3kreNvS6hFZhVU5g+uY/30l42jbgt0XGcNBEmBDGJR71J692V92tA==. (260 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN lifecycle nysocks@1.2.9~install: cannot run in wd %s %s (wd=%s) nysocks@1.2.9 node-gyp rebuild /root/nysocks
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN nysocks@1.2.9 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 239 packages in 13.758s
root@vps:~/nysocks#

还是遇错，怎么解决？

**Comment by luckypoem** [comment]
或者你可以上传可执行文件到https://github.com/oyyd/nysocks/releases/ 这里吗

**Comment by oyyd** [comment]
@luckypoem 试试把

```
npm i --production
```

换成

```
npm i --production --unsafe-perm
```

从上面的反馈看，我猜应该跟你安装node的方式有关系。关联： https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd

我现在确实是想把node和编译后的代码打包起来，发到release上，跳过本地编译环节。

**Comment by oyyd** [comment]
@luckypoem 或者试试用exectuable https://github.com/oyyd/nysocks/releases/tag/1.2.10

**Comment by luckypoem** [comment]
1.换成
npm i --production --unsafe-perm, 还是遇到同样的错误。

2.在服务器和mac上，分别下载了相应的可执行文件，但是：
root@ar:~/nysocks# ./nysocks_v1.2.10_linux_x64
pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: Cannot find module '../../build/Release/addon.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/nysocks/node/lib/socket.js:18:14)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
root@ar:~/nysocks#

在mac上，
yudeMacBook-Air:nysocks brite$ ./nysocks_v1.2.10_mac
pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: Cannot find module '../../build/Release/addon.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/nysocks/node/lib/socket.js:18:14)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
yudeMacBook-Air:nysocks brite$ 

怎么解决？

**Comment by oyyd** [comment]
@luckypoem 我更新了assets，你再重新试一下。

https://github.com/zeit/pkg/issues/329 pkg现在不支持node addon，我之前看错了。现在我是手动把binary打包进去了。

**Comment by luckypoem** [comment]
现在正常了，翻墙很快呢。非常感谢

**Comment by oyyd** [comment]
感谢您耐心的反馈。

**Comment by luckypoem** [comment]
hello
这条命令./nysocks_v1.2.10_linux_x64 server -p 20000 -k my-password -m fast 无论以screen方式，daemonize方式，还是以> /dev/null &方式，都维持不了多久就会退出。以forever方式或pm2方式运行也是无效的，所以干脆直接运行
./nysocks_v1.2.10_linux_x64 server -p 20000 -k my-password -m fast ,保持这个终端窗口不关闭即可.
但是这样也维持不了多久，因为vps会断开连接导致nysocks_v1.2.10_linux_x64进程会跟着退出。

所以可否把它做成用systemd来控制从而在后台运行呢？

**Comment by oyyd** [comment]
@luckypoem systemd会有不少额外的工作量，而且我想尽可能保证nysocks在windows上也能正确运行。你也可以考虑利用`> /dev/null &`和nohup一起运行。

不过现在pm2的方式应该是有效的，我检查了一下可能还是pkg打包时漏掉了些文件导致现在使用无效，我稍后重新打包上传一下。

**Comment by oyyd** [comment]
@luckypoem 可以重新下载一下assets再尝试一下`-d`选项，`nysocks client -s`可以查看进程状态。之前没有在node上打包的经验，请多多谅解

**Comment by luckypoem** [comment]
还是不行，用nodemon也不行。
root@ar:~/nysocks_v1.2.10_linux_x64# nodemon ./nysocks server -p 20000 -k my-password -m fast
[nodemon] 1.17.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./nysocks server -p 20000 -k iloveson -m fast`
/root/nysocks_v1.2.10_linux_x64/nysocks:1
(function (exports, require, module, __filename, __dirname) { ELF
                                                              ^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
[nodemon] app crashed - waiting for file changes before starting...

我有一点不明白，可执行文件不是一个文件就够了吗？你的压缩包里的build目录有何作用？

我看到pm2/forever/nodemon的用法分别是：
pm2 start xyz.js
forever start xyz.js
nodemon xyz.js
所以，可否上传作为可执行文件用途的js文件呢？

**Comment by oyyd** [comment]
不需要其它应用了，`./nysocks server -p 20000 -k PASSWORD -m fast -d start`即可，pm2是内置在nysocks里面了

**Comment by luckypoem** [comment]
你这条命令是无效的，我运行lsof -i:20000 什么也没输出，说明nysocks 实际上并未在运行中。

**Comment by luckypoem** [comment]
这里http://www.ruanyifeng.com/blog/2016/03/systemd-tutorial-commands.html 和这里 http://www.ruanyifeng.com/blog/2016/03/systemd-tutorial-part-two.html ，你看看。我没看懂。
看能不能用systemd把nysocks以daemon方式运行
