### ISSUE TITLE
网络情况正常，但客户端断开后，无法连接上服务端

### ISSUE THREAD

**Issue by hxhxd** [oyyd/nysocks#6]
作者你好，谢谢你的nysocks，效果不错。  
只是遇到这问题：一段时间闲置后/客户端机器休眠恢复后，就无法使用了。偶尔服务端和客户端重开后恢复。但大多数情况下，需要更换端口再启动才能恢复。  
表现是重启的话到 “PAC service is listening on 8090” 这里就不能继续了，socks5那行出不来。  
或者就是一直 “connecting...”   

请问我该如何进一步排查问题，找出原因所在？  
谢谢 ：）

**Comment by oyyd** [comment]
nysocks客户端和服务端之间是有连接状态的。

正常情况下会在无法连接网络的情况下，或是ip发生变化的情况下断开;在有网络连接后尝试重新连接。重新连接的过程一般不会超过5s，所以切换网络后可以稍等一会。

但是看你后面的描述，即使你手动重启，仍旧连接不上（没有显示socks服务），我怀疑应该还是你网络本身的问题。

**Comment by hxhxd** [comment]
网络的话，使用是正常的。换其他梯子也正常使用着啊。
不知道问题出在哪儿，所以想请教一下怎么排查

**Comment by oyyd** [comment]
我在想有什么方式排查，可能需要开启debug模式，然后收集一些信息。我本地没法复现的情况会很难处理。

**Comment by hxhxd** [comment]
好的，有方案了请再@我，我再依法处理 ：）  
Thanks again :)

**Comment by oyyd** [comment]
Fixed in 2.x.
